# Generated by Django 5.1 on 2024-11-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default='Untitled Chat', max_length=100),
        ),
    ]
